# -*- coding: utf-8 -*-
"""code20

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RWtz6ObdSU_G9AdDH9_0xpUccQWFME9C
"""

for i in range(1, 6):
    print(f"Square of {i} is {i * i}")

text = "Hello"
for char in text:
    print(char)

